import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"
import { AppUtilsProvider } from "@/context/AppUtils";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import 'bootstrap-icons/font/bootstrap-icons.css';


export const metadata: Metadata = {
  title: "Firma de recibos digitales",
  description: "Generated by acorrea",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Estructura flex de 100vh */}
      <body className="d-flex flex-column min-vh-100 bg-light">
        <AppUtilsProvider>
       
          <Toaster />          

          {/* Contenido principal (crece para empujar el footer abajo) */}
          <main className="flex-grow-1 container-fluid">
            {children}
          </main>

          <Footer />

        </AppUtilsProvider>
      </body> 
    </html>
  );
}
